{
  "Uuid": "33bea800-6a62-4baf-a2de-a0511de07f98",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Shp_ConvexHull",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementsSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "81b0eb84-f673-457a-8ffb-331eb9d90707-0003efba",
        "81b0eb84-f673-457a-8ffb-331eb9d90707-0003efe0",
        "81b0eb84-f673-457a-8ffb-331eb9d90707-0003efff",
        "81b0eb84-f673-457a-8ffb-331eb9d90707-0003f027",
        "81b0eb84-f673-457a-8ffb-331eb9d90707-0003f04f",
        "81b0eb84-f673-457a-8ffb-331eb9d90707-0003f0b6",
        "81b0eb84-f673-457a-8ffb-331eb9d90707-0003f100",
        "81b0eb84-f673-457a-8ffb-331eb9d90707-0003f13d"
      ],
      "Id": "f853b726cdd24aa1a35d220b96d2ecee",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b856b02f271a45039c9aadbbfd5fac41",
          "Name": "Elements",
          "Description": "Eléments sélectionnés.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Sélectionner plusieurs éléments dans le document Revit."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "80717b03ca8944e9b894514c6b41fab1",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "8f08f67f7d39412fbc7975b4075a721c",
          "Name": "detailCurve",
          "Description": "Revit.Elements.DetailCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "71d0fb51043a498b8fd5751bfe7d0d74",
          "Name": "Curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Revit.Elements.DetailCurve.Curve",
      "Replication": "Auto",
      "Description": "Obtenir la courbe de géométrie\n\nDetailCurve.Curve: Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "3353072a-b97d-4b70-9e15-00d5daf7c19a",
      "FunctionType": "Graph",
      "Id": "ff2ec379c68e426192a405edc602c515",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "62f71c41dc9e4852a89c72bf3ac09447",
          "Name": "_DynGeometry",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "452ef9d8eff049fd8857ea79bf614f8e",
          "Name": "_ShpGeometry",
          "Description": "valeur de retour",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Converts Dynamo geometry to Shapely geometry."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "9689422b963c45e7b259e344e0b6b9be",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "2ead7d226fae414d957a43da85ddbb98",
          "Name": "curves",
          "Description": "Courbes à joindre pour former la polycurve\n\nCurve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bf8023ee1d81494dbb226cdaee26e54d",
          "Name": "joinTolerance",
          "Description": "Tolérance pour déterminer la taille de l'écart autorisé entre les courbes à joindre\n\ndouble\nValeur par défaut : 0.001",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d74b0e432e39404a855435334b78abc7",
          "Name": "trimCurves",
          "Description": "bool\nValeur par défaut : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "639e1a3cf9724a60892e9fb4be9bd7e5",
          "Name": "trimLength",
          "Description": "double\nValeur par défaut : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "92dfcd8d8fb842739f8548557c6a39e8",
          "Name": "PolyCurve",
          "Description": "Polycourbe créée par des courbes jointes",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.ByJoinedCurves@Autodesk.DesignScript.Geometry.Curve[],double,bool,double",
      "Replication": "Auto",
      "Description": "Créer une PolyCurve en joignant les courbes. Inverse la courbe selon les besoins pour la connectivité. Choisissez une tolérance de jonction entre 1e-6 et 1e-3.\n\nPolyCurve.ByJoinedCurves (curves: Curve[], joinTolerance: double = 0.001, trimCurves: bool = false, trimLength: double = 0): PolyCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "67213d40-841d-4b3d-9a3a-6371f965a4b3",
      "FunctionType": "Graph",
      "Id": "f73c5251a4fc4ca1a9e716352e4106c2",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "e2484d6d47f847f7891ae9da29b038ef",
          "Name": "_ShpGeometry",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e783fc0a9d6246e3ace9f43a0d12555f",
          "Name": "_DynGeometry",
          "Description": "valeur de retour",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Converts Shapely geometry to Dynamo geometry."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "WatchWidth": 72.0,
      "WatchHeight": 38.0,
      "Id": "4b99616bcf7a43bfaea2f4fcbad4b331",
      "NodeType": "ExtensionNode",
      "Inputs": [
        {
          "Id": "72b2ec68e08f4da6851587b129effd85",
          "Name": "",
          "Description": "Afficher la sortie de ce noeud",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "691b56e542164ad0874d23dbc3da609f",
          "Name": "",
          "Description": "Sortie du noeud",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualiser la sortie du noeud"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "6a76e169b6c94eb6813aeb6c061091b7",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "8d52a62d31f34cc8844eac4a786f9f64",
          "Name": "geometry",
          "Description": "La géométrie à laquelle vous souhaitez appliquer une couleur.\n\nGeometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "987e05fcc82b43a0887e75d2a5ea7767",
          "Name": "color",
          "Description": "La couleur.\n\nColor",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b934f605d15e495a82420b3e0bb1e280",
          "Name": "GeometryColor",
          "Description": "Un objet d'affichage.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Modifiers.GeometryColor.ByGeometryColor@Autodesk.DesignScript.Geometry.Geometry,DSCore.Color",
      "Replication": "Auto",
      "Description": "Afficher la géométrie à l'aide d'une couleur.\n\nGeometryColor.ByGeometryColor (geometry: Geometry, color: Color): GeometryColor"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.ColorPalette, CoreNodeModels",
      "InputValue": {
        "R": 255,
        "G": 0,
        "B": 0,
        "A": 255
      },
      "Id": "d71615be06b84d7ea02530dd756b1a8b",
      "NodeType": "ColorInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "8cd4a46a084546b7af38a2e143a9785a",
          "Name": "Color",
          "Description": "Selected Color.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Sélectionner une couleur dans la palette"
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "WatchWidth": 72.0,
      "WatchHeight": 38.0,
      "Id": "7b17a1ea263442e2ba1f95228586c2a9",
      "NodeType": "ExtensionNode",
      "Inputs": [
        {
          "Id": "83d2ca38ab654f55a114eb96c662fbc0",
          "Name": "",
          "Description": "Afficher la sortie de ce noeud",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "55ec050fbe54439b9f16edf609f6ee7f",
          "Name": "",
          "Description": "Sortie du noeud",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualiser la sortie du noeud"
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "WatchWidth": 420.0,
      "WatchHeight": 38.0,
      "Id": "fbf6bb027d3b4a5a9c1bfead5918e7ed",
      "NodeType": "ExtensionNode",
      "Inputs": [
        {
          "Id": "e3979fb73d4b4704b90503660243ed54",
          "Name": "",
          "Description": "Afficher la sortie de ce noeud",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3444f46b7f6444559b85f8d90ed93541",
          "Name": "",
          "Description": "Sortie du noeud",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualiser la sortie du noeud"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "cbb374632f1741b082c7ccfc22ca367c",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "70948e91f0a24c60a0143bea430956bc",
          "Name": "closedCurve",
          "Description": "Courbe fermée utilisée comme limite de surface\n\nCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6c351ce498fc49268bc76ff6ec9bfff0",
          "Name": "Surface",
          "Description": "Surface créée par correction",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByPatch@Autodesk.DesignScript.Geometry.Curve",
      "Replication": "Auto",
      "Description": "Créer une surface en remplissant l'intérieur d'un contour fermé défini par les Curves d'entrée.\n\nSurface.ByPatch (closedCurve: Curve): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "4dc7e6c2-89ba-4a63-ada9-fcf599de8d6e",
      "FunctionType": "Graph",
      "Id": "6e00610953884c7fbc4cbe4745981250",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "cfdb13bf4b03415699aba2083d65b1d0",
          "Name": "_ShpGeometry",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "af26e16668854abda228025eda2d8b55",
          "Name": "_ShpGeometry",
          "Description": "valeur de retour",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "It forms the smallest convex polygon that encompasses the entire geometry or set of points. The resulting geometry is a boundary that surrounds all points without containing any concave indentations."
    }
  ],
  "Connectors": [
    {
      "Start": "b856b02f271a45039c9aadbbfd5fac41",
      "End": "8f08f67f7d39412fbc7975b4075a721c",
      "Id": "d55d2ec77bb14d62810c38d4c5195eb0",
      "IsHidden": "False"
    },
    {
      "Start": "71d0fb51043a498b8fd5751bfe7d0d74",
      "End": "2ead7d226fae414d957a43da85ddbb98",
      "Id": "8c1cfd24c5fd485e9e58afc6711e3f3e",
      "IsHidden": "False"
    },
    {
      "Start": "452ef9d8eff049fd8857ea79bf614f8e",
      "End": "cfdb13bf4b03415699aba2083d65b1d0",
      "Id": "3062401535674bcab0a134439aa67ee0",
      "IsHidden": "False"
    },
    {
      "Start": "92dfcd8d8fb842739f8548557c6a39e8",
      "End": "70948e91f0a24c60a0143bea430956bc",
      "Id": "ecd4edbf0057479c9c7f31d1cfdb7483",
      "IsHidden": "False"
    },
    {
      "Start": "e783fc0a9d6246e3ace9f43a0d12555f",
      "End": "72b2ec68e08f4da6851587b129effd85",
      "Id": "01120da022c142848c6da7797b652076",
      "IsHidden": "False"
    },
    {
      "Start": "691b56e542164ad0874d23dbc3da609f",
      "End": "8d52a62d31f34cc8844eac4a786f9f64",
      "Id": "963f63308ce442c1a3f1d17bc6a9917d",
      "IsHidden": "False"
    },
    {
      "Start": "8cd4a46a084546b7af38a2e143a9785a",
      "End": "987e05fcc82b43a0887e75d2a5ea7767",
      "Id": "e1fe2d3526524d1db1fdf587bdc17707",
      "IsHidden": "False"
    },
    {
      "Start": "6c351ce498fc49268bc76ff6ec9bfff0",
      "End": "62f71c41dc9e4852a89c72bf3ac09447",
      "Id": "325008ea3d3644c7b977b59a44ebc570",
      "IsHidden": "False"
    },
    {
      "Start": "6c351ce498fc49268bc76ff6ec9bfff0",
      "End": "83d2ca38ab654f55a114eb96c662fbc0",
      "Id": "f9dfe68c75464bf9a2e54dff0c47f6b4",
      "IsHidden": "False"
    },
    {
      "Start": "af26e16668854abda228025eda2d8b55",
      "End": "e2484d6d47f847f7891ae9da29b038ef",
      "Id": "a8b2d7e3ad484dfc8bc6837d6df3029a",
      "IsHidden": "False"
    },
    {
      "Start": "af26e16668854abda228025eda2d8b55",
      "End": "e3979fb73d4b4704b90503660243ed54",
      "Id": "a52da2b20d9e47bba6e7231905c4618f",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [
    "3353072a-b97d-4b70-9e15-00d5daf7c19a",
    "67213d40-841d-4b3d-9a3a-6371f965a4b3",
    "4dc7e6c2-89ba-4a63-ada9-fcf599de8d6e"
  ],
  "NodeLibraryDependencies": [
    {
      "Name": "Dynamo → Shapely.dyf",
      "ReferenceType": "DYFFile",
      "Nodes": [
        "ff2ec379c68e426192a405edc602c515"
      ]
    },
    {
      "Name": "Shapely → Dynamo.dyf",
      "ReferenceType": "DYFFile",
      "Nodes": [
        "f73c5251a4fc4ca1a9e716352e4106c2"
      ]
    },
    {
      "Name": "Shp_ConvexHull.dyf",
      "ReferenceType": "DYFFile",
      "Nodes": [
        "6e00610953884c7fbc4cbe4745981250"
      ]
    }
  ],
  "EnableLegacyPolyCurveBehavior": true,
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Propriétés",
      "Version": "3.4",
      "Data": {}
    },
    {
      "ExtensionGuid": "DFBD9CC0-DB40-457A-939E-8C8555555A9D",
      "Name": "Generative Design",
      "Version": "9.0",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "Aucun",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "3.4.1.7055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Aperçu en arrière-plan",
      "EyeX": -23.24016761779785,
      "EyeY": 19.637636184692383,
      "EyeZ": 4.8433661460876465,
      "LookX": 0.0179443359375,
      "LookY": -19.411396026611328,
      "LookZ": -5.427226543426514,
      "UpX": 0.0031832228414714336,
      "UpY": 0.26926422119140625,
      "UpZ": -0.9630610942840576
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "f853b726cdd24aa1a35d220b96d2ecee",
        "Name": "Select Model Elements",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 222.0,
        "Y": 426.0
      },
      {
        "Id": "80717b03ca8944e9b894514c6b41fab1",
        "Name": "DetailCurve.Curve",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 559.0,
        "Y": 434.0
      },
      {
        "Id": "ff2ec379c68e426192a405edc602c515",
        "Name": "Dynamo → Shapely",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 1488.3749683044857,
        "Y": 524.563675673996
      },
      {
        "Id": "9689422b963c45e7b259e344e0b6b9be",
        "Name": "PolyCurve.ByJoinedCurves",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 861.6920481949846,
        "Y": 445.6262994842813
      },
      {
        "Id": "f73c5251a4fc4ca1a9e716352e4106c2",
        "Name": "Shapely → Dynamo",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2249.6281773430765,
        "Y": 528.6168315381152
      },
      {
        "Id": "4b99616bcf7a43bfaea2f4fcbad4b331",
        "Name": "Watch",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 2591.425712909221,
        "Y": 529.2846497127784
      },
      {
        "Id": "6a76e169b6c94eb6813aeb6c061091b7",
        "Name": "GeometryColor.ByGeometryColor",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 3226.201802091838,
        "Y": 545.3533359727096
      },
      {
        "Id": "d71615be06b84d7ea02530dd756b1a8b",
        "Name": "Color Palette",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 3030.6270776425954,
        "Y": 619.4171369475707
      },
      {
        "Id": "7b17a1ea263442e2ba1f95228586c2a9",
        "Name": "Watch",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 1480.465403798239,
        "Y": 382.59797747589994
      },
      {
        "Id": "fbf6bb027d3b4a5a9c1bfead5918e7ed",
        "Name": "Watch",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 2247.139469449334,
        "Y": 377.04877353754716
      },
      {
        "Id": "cbb374632f1741b082c7ccfc22ca367c",
        "Name": "Surface.ByPatch",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 1199.7122396331001,
        "Y": 523.2748071943915
      },
      {
        "Id": "6e00610953884c7fbc4cbe4745981250",
        "Name": "Shp_ConvexHull",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 1874.0177899847863,
        "Y": 522.1481868839041
      }
    ],
    "Annotations": [],
    "X": -879.6871071626308,
    "Y": 15.914349008546594,
    "Zoom": 0.7650467592618032
  }
}